# ワークフロー名
name: 4限開始10分前

# 実行条件
on:

  schedule:

    # 毎日15:00(JST)
    - cron: "0 6 * * *"

  # 手動実行を有効化
  workflow_dispatch:

jobs:

  reminder:

    runs-on: ubuntu-latest

    steps:

      # リポジトリを取得
      - uses: actions/checkout@v4

      # Pythonをインストール
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ライブラリをインストール
      - run: pip install -r requirements.txt

      # 通知を送信
      - run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "4限開始10分前"
