# ワークフロー名
name: Discord Reminder

# 実行条件
on:
  schedule:
    # 毎日 8:50 JST
    - cron: "50 23 * * *"

    # 毎日 10:40 JST
    - cron: "40 1 * * *"

    # 毎日 13:10 JST
    - cron: "10 4 * * *"

    # 毎日 15:00 JST
    - cron: "0 6 * * *"

    # 毎日 16:50 JST
    - cron: "50 7 * * *"

    # 毎日 19:00 JST
    - cron: "0 10 * * *"

    # 毎日 23:00 JST
    - cron: "0 14 * * *"

    # 毎日 0:00 JST
    - cron: "0 15 * * *"

  # 手動実行も可能
  workflow_dispatch:

jobs:
  reminder:

    # Ubuntu環境で実行
    runs-on: ubuntu-latest

    steps:

      # リポジトリを取得
      - uses: actions/checkout@v4

      # Pythonをセットアップ
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ライブラリをインストール
      - run: pip install -r requirements.txt

      # ==========================
      # 8:50 JST
      # ==========================
      - name: 1限開始10分前
        if: github.event.schedule == '50 23 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "1限開始10分前"

      # ==========================
      # 10:40 JST
      # ==========================
      - name: 2限開始10分前
        if: github.event.schedule == '40 1 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "2限開始10分前"

      # ==========================
      # 13:10 JST
      # ==========================
      - name: 3限開始10分前
        if: github.event.schedule == '10 4 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "3限開始10分前"

      # ==========================
      # 15:00 JST
      # ==========================
      - name: 4限開始10分前
        if: github.event.schedule == '0 6 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "4限開始10分前"

      # ==========================
      # 16:50 JST
      # ==========================
      - name: 帰宅
        if: github.event.schedule == '50 7 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "さっさと帰れ～"

      # ==========================
      # 19:00 JST
      # ==========================
      - name: 晩御飯
        if: github.event.schedule == '0 10 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "晩御飯の時間"

      # ==========================
      # 23:00 JST
      # ==========================
      - name: 23時
        if: github.event.schedule == '0 14 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "なんと、もう11時"

      # ==========================
      # 0:00 JST
      # ==========================
      - name: 就寝
        if: github.event.schedule == '0 15 * * *'
        run: python main.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "さっさと寝ろ～"
